/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110642-g6b2ae90411-20230516"
#endif /* AVUTIL_FFVERSION_H */
